version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    command: postgres -c stats_temp_directory=/tmp
  mssql:
    image: mcr.microsoft.com/mssql/server
    volumes:
      - ./data/mssql/data:/var/opt/mssql/data
      - ./data/mssql/log:/var/opt/mssql/log
      - ./data/mssql/secrets:/var/opt/mssql/secrets
    environment: 
      - MSSQL_PASSWORD=mssql_arise
      - MSSQL_USER=planer
      - ACCEPT_EULA=Y
    command: sudo systemctl start mssql-server
  web:
    build: .
    command: "./django_docker_startup.sh"
    volumes:
      - .:/code
      - ./data:/code/tmp_data
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - MSSQL_PASSWORD=mssql_arise
      - MSSQL_USER=planer
    depends_on:
      - db
      - mssql
