version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    command: postgres -c stats_temp_directory=/tmp
  web:
    build: .
    command: ["./django_prototype/wait-for-it.sh", "db:5432", "--", "python", "django_prototype/manage.py", "runserver", "0.0.0.0:8000"]
    # python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ./data:/code/tmp_data
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
