# Generated by Django 3.2.15 on 2022-09-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={},
        ),
        migrations.RemoveField(
            model_name='machine',
            name='end',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='start',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='title',
        ),
        migrations.AddField(
            model_name='machine',
            name='AKNR',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machine',
            name='End',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='KndNr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machine',
            name='SchrittNr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machine',
            name='Start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='resourceId',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
