# Generated by Django 3.2.15 on 2022-09-06 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_auto_20220906_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='End',
            new_name='Ende',
        ),
    ]
